version: '3.8'

services:
  ollama:
    image: ollama/ollama  # Imagen oficial de Ollama
    container_name: ollama_container
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # Persistencia de modelos
    command: >
      sh -c "
        ollama run llama3.2 || true && 
        ollama pull nomic-embed-text:latest || true && 
        ollama serve
      "
    # Añadir un healthcheck para que otros servicios esperen a que Ollama esté realmente listo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      # Mejor usar 'service_healthy' para asegurar que el servicio está listo, no solo corriendo
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8000:8000"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_BASE_URL=http://backend:8080  # Usar la URL del backend en Docker

volumes:
  ollama_data:
