apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sdiaz15/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_HOST
          value: "http://ollama:11434"

