name: Create AKS Cluster

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-aks:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Crear AKS
      run: |
        az aks create \
          --resource-group grupo-k8s \
          --name mi-cluster-aks \
          --node-count 1 \
          --node-vm-size Standard_D4s_v3 \
          --enable-addons monitoring \
          --generate-ssh-keys
